common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *common
  database: "fieldable_form_example_dev"

test:
  <<: *common
  database: "fieldable_form_example_test"

production:
  <<: *common
  database: "fieldable_form_example_prod"